### ISSUE TITLE
43. STUDENT ENROLLMENT: Modify View

### ISSUE THREAD

**Issue by AnasShafqat** [DEXDEVS/College-CMS#43]
### _Modify the view of `std-enrollment-head:`_
**-------------------------------------------------------------** 

> **NOTE:**

**_Show all the students of the class according to the class enrollment as:_**

**_1. Sr #
2. Student Roll No
3. Student Name_**

**Comment by naumanshahid007** [comment]
Student Enrollment head detail view has been modified
