### ISSUE TITLE
64. STUDENT/EMPLOYEE PROFILE: Modifications

### ISSUE THREAD

**Issue by AnasShafqat** [DEXDEVS/College-CMS#64]
**_Some modifications are required in "Student and Employee" profile which are as follows:_**
**---------------------------------------------------------------------------------------------------**
### Student Profile

**_1. align the edit, send email and send sms buttons
2. change the color of send email and send sms buttons
3. display session and section in "academic info" tab
4. display no. of installments and amount of each installment in "fee details" tab_**

### Employee Profile

**_1. align the edit, send email and send sms buttons
2. change the color of send email and send sms buttons
3. add back button in "emp-reference-update" form_**

**Comment by naumanshahid007** [comment]
Modifications are done
