### ISSUE TITLE
65. URL PRETTIFY: Bugs

### ISSUE THREAD

**Issue by AnasShafqat** [DEXDEVS/College-CMS#65]
**_Remove the URL prettify bugs on the following links:_**
**----------------------------------------------------------**
### Student Profile
**_1. std-guardian-info-update (back button)
2. std-ice-info-update (back button)
3. std-ice-info-update (update button not submitting data)
4. std-academic-info-update (back button)
5. fee details tab (edit button)_**

### Employee Profile

**_1. emp-info-view (Send Email Button)_**

**Comment by Kinza59** [comment]
URL PRETTIFY: bugs removed
